### PR TITLE
System test for GFAL2_SRM2Storage and GFAL2_XROOTStorage

### PR DESCRIPTION
**Pull request by fibbo**
#### Branch:

This tests the new plugins for rel-v6r13: GFAL2_SRM2Storage and GFAL2_XROOTStorage.

#### Plugins:
To run the test following plugins are needed:

* gfal2-2.8.1-1
* gfal2-plugin-xrootd-0.2.2-2
* gfal2-python-1.6.0-1

#### Storage element:

Change self.storageName within the basicTest class to the name of the storageElement you wish to run this test against. This storage element needs to be supporting two access protocols, using the protocolName GFAL2_SRM2 and GFAL2_XROOT respectively. If you want to test only either SRM2 or XROOT remove the other testsuite in the unittest.

### CODE REVIEW

**Comment by fstagni** [comment]
Hi, can you please add some minimal documentation on how to run this test? Is there the need for something deployed? Thanks

**Comment by fibbo** [comment]
Sure, sorry for not including it before. Is this sufficient?

**Comment by fstagni** [comment]
Sure, just add this doc also in the IntegrationGFAL2StorageBase.py (we have this pattern for all these integration tests). Thanks about that.

**Comment by fibbo** [comment]
Done, sorry for the delay.

**Pull request merged**
