### PR TITLE
add testing for recursive and non recursive chown,chmod,chgrp in the DFC

### PR DESCRIPTION
**Pull request by chaen**

### CODE REVIEW

**Comment by fstagni** [comment]
Looks ok, should Jenkins run them?

**Comment by chaen** [comment]
They are in a file that jenkins already run normally

**Comment by fstagni** [comment]
Ok. But, doe this depend on https://github.com/DIRACGrid/DIRAC/pull/2487 ?

**Comment by chaen** [comment]
Yes

**Comment by fstagni** [comment]
So, I'll wait before merging.

**Comment by atsareg** [comment]
Who is supposed to merge the PRs in this project ?

**Comment by fstagni** [comment]
I merge. This one has not been merged because Chris says it depends from the mentioned PR. But if needed I can merge now.

**Pull request merged**
